# Generated by Django 4.2.7 on 2023-12-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(related_name='appuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='appuser_permissions', to='auth.permission'),
        ),
    ]
