# Generated by Django 4.2.7 on 2023-12-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_username_appuser_first_name_appuser_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="major",
            field=models.CharField(default="DefaultMajorValue", max_length=50),
        ),
        migrations.AddField(
            model_name="appuser",
            name="minor",
            field=models.CharField(default="DefaultMinorValue", max_length=50),
        ),
    ]
